### ISSUE TITLE
there is possibility to occupy device and don't return it back into the pool

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-grid#10]
09:13:17.158 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {deviceType=Phone, proxy_port=9011, server:CONFIG_UUID=d1f82fd9-65be-4d73-bba9-52b91ddcd1d2, seleniumProtocol=WebDriver, adb_port=5049, vnc=...:7520, deviceName=Samsung_Galaxy_S8_Plus, version=9, platform=ANDROID, platformVersion=9, automationName=uiautomator2, browserName=Samsung_Galaxy_S8_Plus, maxInstances=1, platformName=ANDROID, udid=...}
09:13:26.526 INFO [RequestHandler.process] - Error forwarding the new session Error forwarding the request org.seleniumhq.jetty9.io.EofException
org.openqa.grid.internal.exception.NewSessionException: Error forwarding the request org.seleniumhq.jetty9.io.EofException
        at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:94)
        at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:114)
        at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
        at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:69)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.openqa.grid.common.exception.ClientGoneException: org.seleniumhq.jetty9.io.EofException
        at org.openqa.grid.internal.TestSession.writeRawBody(TestSession.java:484)
        at org.openqa.grid.internal.TestSession.forward(TestSession.java:278)
        at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:91)
        ... 35 more
Caused by: org.seleniumhq.jetty9.io.EofException
        at org.seleniumhq.jetty9.io.ChannelEndPoint.flush(ChannelEndPoint.java:286)
        at org.seleniumhq.jetty9.io.WriteFlusher.flush(WriteFlusher.java:393)
        at org.seleniumhq.jetty9.io.WriteFlusher.write(WriteFlusher.java:277)
        at org.seleniumhq.jetty9.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
        at org.seleniumhq.jetty9.server.HttpConnection$SendCallback.process(HttpConnection.java:802)
        at org.seleniumhq.jetty9.util.IteratingCallback.processing(IteratingCallback.java:241)
        at org.seleniumhq.jetty9.util.IteratingCallback.iterate(IteratingCallback.java:224)
        at org.seleniumhq.jetty9.server.HttpConnection.send(HttpConnection.java:538)
        at org.seleniumhq.jetty9.server.HttpChannel.sendResponse(HttpChannel.java:831)
        at org.seleniumhq.jetty9.server.HttpChannel.write(HttpChannel.java:887)
        at org.seleniumhq.jetty9.server.HttpOutput.write(HttpOutput.java:239)
        at org.seleniumhq.jetty9.server.HttpOutput.write(HttpOutput.java:215)
        at org.seleniumhq.jetty9.server.HttpOutput.write(HttpOutput.java:540)
        at java.base/java.io.OutputStream.write(OutputStream.java:122)
        at org.openqa.grid.internal.TestSession.writeRawBody(TestSession.java:482)
        ... 37 more
Caused by: java.io.IOException: Connection reset by peer
        at java.base/sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:182)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:130)
        at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:496)
        at org.seleniumhq.jetty9.io.ChannelEndPoint.flush(ChannelEndPoint.java:266)
        ... 51 more

**Comment by vdelendik** [comment]
it should be fixed indirectly by #54. max delay between sessions even if STF is marked as occupied will be newCommandTimeout in appium. as only device is available in grid it might be used by automation. no need to repro and test
