### ISSUE TITLE
Unable to connect Mcloud-grid  by STF token 

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-grid#40]
**Test scenario:**

1.Open Demo.zebrunner.farm/stf
2.Click Settings
3.Click Keys
4.Generate Access token and copy to clipboard
5.nano zebrunner/mcloud/variables.env
6.Paste Access token
7.Open Jenkins
8.Run Mobile-Android-Demo-Test
9.docker logs -f mcloud-grid

**Actual result**: Unable to connect Mcloud-grid by STF token 

`18:27:06.155 ERROR [HttpClient$Executor.lambda$execute$6] - HTTP call 'GET http://demo.zebrunner.farm:80/api/v1/user' failed with status '500'. Failure #1. Retrying. 
18:27:16.162 ERROR [HttpClient$Executor.lambda$execute$6] - HTTP call 'GET http://demo.zebrunner.farm:80/api/v1/user' failed with status '500'. Failure #2. Retrying. 
18:27:26.174 ERROR [HttpClient$Executor.lambda$execute$6] - HTTP call 'GET http://demo.zebrunner.farm:80/api/v1/user' failed with status '500'. Failure #3. Retrying. 
18:27:26.186 ERROR [HttpClient$Executor.lambda$execute$7] - HTTP call 'GET http://demo.zebrunner.farm:80/api/v1/user' failed with status '500'. Max retries exceeded. 
18:27:26.187 ERROR [STFClient.<init>] - Required STF connection not established! URL: 'http://demo.zebrunner.farm:80'; Token: '50c5432cfa744fd08da22d119b6628e690c92124b4764167ac76eafb3c9d60ad'; Error code: 500
18:27:26.188 ERROR [DefaultGridRegistry.assignRequestToProxy] - Unhandled exception in Matcher thread.
java.lang.RuntimeException: Unable to connect to STF!
	at com.zebrunner.mcloud.grid.integration.client.STFClient.<init>(STFClient.java:72)
	at com.zebrunner.mcloud.grid.MobileRemoteProxy.getSTFClient(MobileRemoteProxy.java:349)
	at com.zebrunner.mcloud.grid.MobileRemoteProxy.getNewSession(MobileRemoteProxy.java:98)
	at org.openqa.grid.internal.ProxySet.lambda$getNewSession$3(ProxySet.java:130)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.grid.internal.ProxySet.getNewSession(ProxySet.java:132)
	at org.openqa.grid.internal.DefaultGridRegistry.takeRequestHandler(DefaultGridRegistry.java:251)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.openqa.grid.internal.NewSessionRequestQueue.processQueue(NewSessionRequestQueue.java:87)
	at org.openqa.grid.internal.DefaultGridRegistry.assignRequestToProxy(DefaultGridRegistry.java:236)
	at org.openqa.grid.internal.DefaultGridRegistry.access$200(DefaultGridRegistry.java:44)
	at org.openqa.grid.internal.DefaultGridRegistry$Matcher.run(DefaultGridRegistry.java:192)
18:27:41.200 ERROR [HttpClient$Executor.lambda$execute$6] - HTTP call 'GET http://demo.zebrunner.farm:80/api/v1/user' failed with status '500'. Failure #1. Retrying. 
18:27:51.209 ERROR [HttpClient$Executor.lambda$execute$6] - HTTP call 'GET http://demo.zebrunner.farm:80/api/v1/user' failed with status '500'. Failure #2. Retrying. 
18:28:01.219 ERROR [HttpClient$Executor.lambda$execute$6] - HTTP call 'GET http://demo.zebrunner.farm:80/api/v1/user' failed with status '500'. Failure #3. Retrying. 
18:28:01.228 ERROR [HttpClient$Executor.lambda$execute$7] - HTTP call 'GET http://demo.zebrunner.farm:80/api/v1/user' failed with status '500'. Max retries exceeded. 
18:28:01.228 ERROR [STFClient.<init>] - Required STF connection not established! URL: 'http://demo.zebrunner.farm:80'; Token: '50c5432cfa744fd08da22d119b6628e690c92124b4764167ac76eafb3c9d60ad'; Error code: 500
18:28:01.229 ERROR [DefaultGridRegistry.assignRequestToProxy] - Unhandled exception in Matcher thread.
java.lang.RuntimeException: Unable to connect to STF!`

**Comment by dhreben** [comment]
Not reproduced.
Closed
