### ISSUE TITLE
remove non-w3c caps usage

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-grid#89]
as we plan to integrate appium 2.0 we can't use anymore non w3c caps without prefix.
as result we see:
```
2023-05-30 13:22:44:880 - [HTTP] [HTTP] {"desiredCapabilities":{"appium:provider":"mcloud","appium:enableVideo":true,"server:CONFIG_UUID":"a6e5f3e5-ba2b-4970-b4f1-d3061e0c4b26","appium:locale":"US","appium:language":"en","appium:remoteAppsCacheLimit":0,"appium:automationName":"UIAutomator2","appium:enableLog":true,"slotCapabilities":{"deviceType":"Phone","proxy_port":7423,"server:CONFIG_UUID":"a6e5f3e5-ba2b-4970-b4f1-d3061e0c4b26","seleniumProtocol":"WebDriver","adb_port":7422,"deviceName":"HTC_10","platform":"ANDROID","platformVersion":"8.0.0","automationName":"uiautomator2","remoteURL":"demo.zebrunner.farm:7425","maxInstances":1,"platformName":"android","udid":"FA74SBN02369"},"appium:deviceName":"ANY","platformName":"android","appium:app":"https://qaprosoft.s3-us-west-2.amazonaws.com/carinademoexample.apk"},"capabilities":{"firstMatch":[{"appium:app":"https://qaprosoft.s3-us-west-2.amazonaws.com/carinademoexample.apk","appium:automationName":"UIAutomator2","appium:deviceName":"ANY","appium:enableLog":true,"appium:enableVideo":true,"appium:lang...
2023-05-30 13:22:44:880 - [debug] [AppiumDriver@e2bd] [AppiumDriver@e2bd] Calling AppiumDriver.createSession() with args: [{"appium:provider":"mcloud","appium:enableVideo":true,"server:CONFIG_UUID":"a6e5f3e5-ba2b-4970-b4f1-d3061e0c4b26","appium:locale":"US","appium:language":"en","appium:remoteAppsCacheLimit":0,"appium:automationName":"UIAutomator2","appium:enableLog":true,"slotCapabilities":{"deviceType":"Phone","proxy_port":7423,"server:CONFIG_UUID":"a6e5f3e5-ba2b-4970-b4f1-d3061e0c4b26","seleniumProtocol":"WebDriver","adb_port":7422,"deviceName":"HTC_10","platform":"ANDROID","platformVersion":"8.0.0","automationName":"uiautomator2","remoteURL":"demo.zebrunner.farm:7425","maxInstances":1,"platformName":"android","udid":"FA74SBN02369"},"appium:deviceName":"ANY","platformName":"android","appium:app":"https://qaprosoft.s3-us-west-2.amazonaws.com/carinademoexample.apk"},null,{"firstMatch":[{"appium:app":"https://qaprosoft.s3-us-west-2.amazonaws.com/carinademoexample.apk","appium:automationName":"UIAutomator2","appium:deviceName":"ANY","appium:enableLog":true,"appium:enableVideo":true,"appium:language":"en","appium:locale":"US",...
2023-05-30 13:22:44:880 - [debug] [AppiumDriver@e2bd] [AppiumDriver@e2bd] Event 'newSessionRequested' logged at 1685452964880 (13:22:44 GMT+0000 (Coordinated Universal Time))
2023-05-30 13:22:44:881 - [Appium] [Appium] Could not parse W3C capabilities: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: platformVersion,udid,enableVnc
2023-05-30 13:22:44:881 - [debug] [AppiumDriver@e2bd] [AppiumDriver@e2bd] Event 'newSessionStarted' logged at 1685452964881 (13:22:44 GMT+0000 (Coordinated Universal Time))
2023-05-30 13:22:44:882 - [debug] [AppiumDriver@e2bd] [AppiumDriver@e2bd] Encountered internal error running command: InvalidArgumentError: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: platformVersion,udid,enableVnc
2023-05-30 13:22:44:882 - [debug] [AppiumDriver@e2bd] [AppiumDriver@e2bd]     at parseCaps (/usr/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:252:11)
2023-05-30 13:22:44:882 - [debug] [AppiumDriver@e2bd] [AppiumDriver@e2bd]     at processCapabilities (/usr/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:332:43)
2023-05-30 13:22:44:882 - [debug] [AppiumDriver@e2bd] [AppiumDriver@e2bd]     at parseCapsForInnerDriver (/usr/lib/node_modules/appium/lib/utils.js:135:40)
2023-05-30 13:22:44:882 - [debug] [AppiumDriver@e2bd] [AppiumDriver@e2bd]     at AppiumDriver.createSession (/usr/lib/node_modules/appium/lib/appium.js:251:49)
2023-05-30 13:22:44:882 - [debug] [AppiumDriver@e2bd] [AppiumDriver@e2bd]     at commandExecutor (/usr/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:106:18)
2023-05-30 13:22:44:882 - [debug] [AppiumDriver@e2bd] [AppiumDriver@e2bd]     at AppiumDriver.executeCommand (/usr/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:123:15)
2023-05-30 13:22:44:882 - [debug] [AppiumDriver@e2bd] [AppiumDriver@e2bd]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-05-30 13:22:44:882 - [debug] [AppiumDriver@e2bd] [AppiumDriver@e2bd]     at defaultBehavior (/usr/lib/node_modules/appium/lib/appium.js:680:16)
2023-05-30 13:22:44:882 - [debug] [AppiumDriver@e2bd] [AppiumDriver@e2bd]     at AppiumDriver.executeWrappedCommand (/usr/lib/node_modules/appium/lib/appium.js:774:16)
2023-05-30 13:22:44:882 - [debug] [AppiumDriver@e2bd] [AppiumDriver@e2bd]     at AppiumDriver.executeCommand (/usr/lib/node_modules/appium/lib/appium.js:696:17)
2023-05-30 13:22:44:882 - [debug] [AppiumDriver@e2bd] [AppiumDriver@e2bd]     at asyncHandler (/usr/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:387:19)
```

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud-grid/pull/90

appium android test was executed successfully.
